### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by trevorsee** [OOKB/mgs2018#12]
I'm trying to add the back button action to the top-left logo. Is it possible you can't put an onClick on  <object>?

**Comment by webmasterkai** [comment]
I'm not sure if the styles allow for the button to be clicked?

**Comment by bjornmeansbear** [comment]
In my 10 minutes I just spent I didn't yet find a CSS rule that solve the issue, though there is definitely a hover state that could be invented

**Comment by bjornmeansbear** [comment]
Potential hack: position a button/link we know works over it styled invisibly?

**Comment by webmasterkai** [comment]
Made the surrounding div a button and gave it inline height/width so it was clickable. There's some delay in switching pages but it works. https://github.com/OOKB/mgs2018/commit/85673903e2de6564520475d2ecd7e6efba7efa69
