### ISSUE TITLE
Extras

### ISSUE THREAD

**Issue by trevorsee** [OOKB/mgs2018#13]
- [ ] on-view-now feature, for show list
- [ ] expand/collapse student lists
- [x] documentation images added to Event page
- [ ] make loading text the theme color

**Comment by webmasterkai** [comment]
The airtable processing script has been adjusted to include documentation image info.
Example: https://console.firebase.google.com/project/mgs-2018/database/mgs-2018/data/entity/Show/recBiZ2Oi5ZX4afSS/documentation/attEYrS9nCbvB8TBC

`url` prop: https://dl-air.imgix.net/YcE8R468TzW7X1umbPSz_Depart%20Africa-14.JPG?w=200

They should probably be converted to work the way other images do but this will work for now.

**Comment by trevorsee** [comment]
Closing to make individual issues
