### ISSUE TITLE
Be able to directly view non student pages for testing/dev

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/mgs2018#5]
1. Is there a way for me to see a student-page for my user? So that I can upload images and test/style it

**Comment by webmasterkai** [comment]
I think if we add the necessary info to the https://console.firebase.google.com/project/mgs-2018/database/mgs-2018/data/entity/Student database it will allow that user to show up.

**Comment by trevorsee** [comment]
Not needed anymore, closing
